config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/characters', to: 'characterpage#index', as: 'characters'
  get '/episodes', to: 'episodes#index', as: 'episodes'
  get '/locations', to: 'location#index', as: 'locations'
  get '/quiz', to: 'quiz#index', as: 'quiz'


  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  def index
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characterpage_controller.rb
class CharacterpageController < ApplicationController

  def index
  end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def index
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def index
  end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characterpage_helper.rb
module CharacterpageHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/characterpage/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="characterpage.scss">
  </head>

  <body>
    <div class="title">
      <h1>All 493 Characters</h1>
    </div>
    <div class="container">
      <script src="main.js"></script>
    </div>
  </body>
</html>

app/views/episodes/index.html.erb
<h2>EPISODES!</h2>

app/views/home/index.html.erb
<head>
  <link rel="stylesheet" href="home.scss">
</head>

<div class="title">
  <h1>Chronenberg University</h1>
</div>
<div class="quote">
  <h4>"And this is why you don't invite a Floopy Doop and a Shmoopy Doop to the same party."</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RMrails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="navbar">
    <ul class="nav navbar-nav">
      <a><%= link_to 'Home', root_path %></a>
      <a><%= link_to 'Edpisodes', episodes_path%></a>
      <a><%= link_to 'Character List', characters_path %></a>
      <a><%= link_to 'Locations', locations_path %></a>
      <a><%= link_to 'Quiz', quiz_path %></a>
    </ul>
    <ul class="nav navbar-nav pull-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <a><%= link_to 'Profile', edit_user_registration_path %></a>
            <a><%= link_to 'Log out', destroy_user_session_path, method: :delete %></a>
          </ul>
        </a>
      <% else %>
        <a><%= link_to 'Log In', new_user_session_path %></a>
        <a><%= link_to 'Sign Up', new_user_registration_path %></a>
      <% end %>
    </ul>
  </div>
  <% flash.each do |key, value| %>
    <%= value %>
  <% end %>
  
  <%= yield %>
  </body>
</html>

app/views/location/index.html.erb
<h1>Locations!</h1>

app/views/quiz/index.html.erb
<h1>Quiz!</h1>